version: 2.1
orbs:
  node: circleci/node@4.1.0
jobs:
  build:
    docker:
      - image: circleci/node:14
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
      - persist_to_workspace:
          root: ~/repo
          paths:
            - .

  deploy:
    machine:
      enabled: true
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Correct Ownership
          command: |
            ssh ubuntu@15.237.117.49 \<< EOF
              sudo chown -R ubuntu:ubuntu /var/www/store
            EOF

      - run:
          name: Remove Store Folder
          command: |
            ssh ubuntu@15.237.117.49 'rm -rf /var/www/store/*'
      - run:
          name: Copy HTML Files
          command: |
            scp -r ~/repo/* ubuntu@15.237.117.49:/var/www/store
      - run:
          name: Deploy Over SSH
          command: |
            ssh ubuntu@15.237.117.49 \<< EOF
              cd /var/www/
              git pull
              npm install
              pm2 restart all
            EOF

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
